### ISSUE TITLE
feat: function support in user config

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/unhead-schema-org#6]
### Clear and concise description of the problem

Currently the host user config requires a type of string. I might want to provide own logic to decide which host is to be used, but I'm not able to provide anything other than a single string.

### Suggested solution

Wouldn't it make sense to also support functions which return strings?

### Alternative

Also, the default could be `window.location.origin` on client side and `event.node.req.headers.host` on server side.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by harlan-zw** [comment]
Hey, there's an example for overriding the host here: https://unhead-schema-org.harlanzw.com/integrations/nuxt/module#nuxtapp-hooks. 

Within Nuxt you can't use a function from nuxt.config.ts in an app context so that's the only way to do it.

I'd prefer not to provide defaults and make the user define them as the host needs to be the canonical host, so it could introduce SEO issues if you were to rely on the defaults

I have pushed up a change as well which will let you set the host using runtime config, allowing you to use .env file too. 

Set a default in nuxt.config.ts

```ts
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      siteUrl: 'https://harlanzw.com/',
    }
  },
})
```

Override it with .env
```
NUXT_PUBLIC_SITE_URL=https://staging.harlanzw.com/
```

Let me know if you have any questions on that
